### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by b-t-k** [btaylor8/theodore-roosevelt_an-autobiography#1]
- run typogrify & clean
- run modernize-spelling

# toc
I am not sure about this. I would personally make the appendices one level lower than the chapters, but I don't know of that's what has been done in other cases.

VII: The War of America the Unready  
	>Appendicies to Chapter VII  
	>>	Appendix A  
	>>	Appendix B  

# endnotes
- line 111: unsemanticated `<i>` See previous endnote.

# chapter 1
- that's not the title: `<i epub:type="se:name.publication.book"><abbr>Mr.</abbr> Gray</i>` — it should be *The Poems of Mr Gray*
- add language tags to `<i epub:type="se:name.publication.poem">Nibelungenlied</i>`

# Chapter 3 + 9
Drama formatted tables should have `<section epub:type="z3998:drama  z3998:scene">` and then use normal drama css

# Content.opf
**long desc** 
- has wrong tense/agreement: "achievements include trust busting… settled … established… etc." should be "settling …establishing… etc."
- "numerous positions he served [in] during" (or maybe "positions he held"?)

**Comment by btaylor8** [comment]
- [x] run typogrify & clean: `se typogrify` inserts u+00a0 after the "Dr." in the chapter 1 receipt; however this isn't needed here because "Dr." does not mean "doctor" in this instance, it is used in the sense "debit record." To prevent `se typogrify` from flagging this, I'm opting to change "Dr." to "DR" (common abbreviation in modern accounting); this also means that it needs the `z3998:initialism` semantic, and adding a lint ignore for t-030. [8b093a8]
- [x] modernize spelling: I opted to leave "The Life-Saving Society" as-is because it was the name of an organization; "any body" is used correctly, so that should not be changed by `se modernize-spelling` either
- [ ] toc: changing appendicies to lower heading levels causes lint errors: s-085 "\<h#\> element found in a \<section\> or a <article> at an unexpected level. Hint: Headings not in the title page start at \<h2\>. If this work has parts, should this header be \<h3\> or higher?"
- [x] endnotes: done [ecdff4d]
- [x] chapter 1 (book title): done [f0f91d1]
- [x] chapter 1 (language tags): done [04e86cb]
- [ ] chapter 3 & 9: waiting on answer from Google Group
- [x] content.opf: done [1f95d39]

**Comment by b-t-k** [comment]
Good stuff. Add the drama tags to the tables please—and update the css. FWIW it is helpful to note exceptions like the modernize-spelling  and typogrify so reviewers don't have to chase them down. I did double check the Life-Saving Society but didn't  notice any body :-)

**Comment by btaylor8** [comment]
All issues have been addressed; this should be ready for review again. Thanks for all the input!
